Repository solana-foundation/anchor, pull requests merged in 2022-11, with the labels that each got.

#2165 Bugfix multiple event listeners with the same name
  CHANGELOG.md
  ts/packages/anchor/src/program/event.ts
Labels: waiting for tests to run

#2155 ts: Remove SPL coders from Anchor package
  .github/actions/setup-ts/action.yaml
  CHANGELOG.md
  tests/custom-coder/Anchor.toml
  tests/custom-coder/package.json
  tests/custom-coder/programs/custom-coder/Cargo.toml
  tests/custom-coder/programs/custom-coder/Xargo.toml
  tests/custom-coder/programs/custom-coder/src/lib.rs
  tests/custom-coder/programs/spl-associated-token/Cargo.toml
  tests/custom-coder/programs/spl-associated-token/src/lib.rs
  tests/custom-coder/programs/spl-token/src/lib.rs
  tests/custom-coder/tests/spl-associated-token-coder.ts
  tests/custom-coder/tests/spl-token-coder.ts
  tests/package.json
  tests/yarn.lock
  ts/build-packages.sh
  ts/packages/anchor/src/coder/index.ts
  ts/packages/anchor/src/coder/spl-associated-token/accounts.ts
  ts/packages/anchor/src/coder/spl-associated-token/events.ts
  ts/packages/anchor/src/coder/spl-associated-token/index.ts
  ts/packages/anchor/src/coder/spl-associated-token/instruction.ts
  ts/packages/anchor/src/coder/spl-associated-token/state.ts
  ts/packages/anchor/src/coder/spl-associated-token/types.ts
  ts/packages/anchor/src/coder/spl-token/accounts.ts
  ts/packages/anchor/src/coder/spl-token/events.ts
  ts/packages/anchor/src/coder/spl-token/index.ts
  ts/packages/anchor/src/coder/spl-token/instruction.ts
  ts/packages/anchor/src/coder/spl-token/state.ts
  ts/packages/anchor/src/coder/spl-token/types.ts
  ts/packages/anchor/src/index.ts
  ts/packages/anchor/src/program/accounts-resolver.ts
  ts/packages/anchor/src/program/namespace/methods.ts
  ts/packages/anchor/src/program/token-account-layout.ts
  ts/packages/anchor/src/spl/associated-token.ts
  ts/packages/anchor/src/spl/index.ts
  ts/packages/anchor/src/spl/token.ts
Labels: waiting for tests to run

#2263 Remove terser for react-native support
  ts/packages/anchor/package.json
  ts/packages/anchor/rollup.config.ts
  ts/yarn.lock
Labels: blocked

#2237 Implement functions to return associated context when fetching accounts.
  ts/packages/anchor/src/program/namespace/account.ts
  ts/packages/anchor/src/utils/rpc.ts
Labels: Looks fine?

#2268 Fix panic parsing seeds when account has qualified path
  lang/syn/src/lib.rs
  tests/pda-derivation/programs/pda-derivation/src/lib.rs
  tests/pda-derivation/programs/pda-derivation/src/other.rs
  tests/pda-derivation/tests/typescript.spec.ts
Labels: waiting for tests to run
