Repository solana-foundation/anchor, pull requests merged in 2022-12, with the labels that each got.

#2200 Add option for jest test scaffolding
  cli/src/lib.rs
  cli/src/template.rs
Labels: waiting for review

#2260 Add support for 256-bit integers in the IDL
  lang/syn/src/idl/mod.rs
  ts/packages/anchor/src/coder/borsh/idl.ts
  ts/packages/anchor/src/coder/common.ts
  ts/packages/anchor/src/idl.ts
  ts/packages/anchor/src/program/namespace/types.ts
  ts/packages/anchor/tests/coder-types.spec.ts
Labels: waiting for tests to run

#2063 fix anchor keys list command
  CHANGELOG.md
  cli/src/lib.rs
Labels: waiting for tests to run

#2153 feat: ata create idempotent and drop rent
  spl/src/associated_token.rs
Labels: waiting for tests to run

#2303 Fixing breaking change where null or undefined wallet throws an error
  CHANGELOG.md
  ts/packages/anchor/src/provider.ts
Labels: waiting for tests to run

#2302 Send all tx logs
  ts/packages/anchor/src/provider.ts
Labels: waiting for tests to run

#2116 Don't use wallet object for account.createInstruction function 2112
  ts/packages/anchor/src/program/namespace/account.ts
Labels: waiting for tests to run

#2016 add geyser_plugin_config support for anchor localnet
  CHANGELOG.md
Labels: AbandonedOrgPR

#1864 cli: run a subset of the test suites
  .github/workflows/tests.yaml
  CHANGELOG.md
  cli/src/config.rs
  cli/src/lib.rs
  tests/multiple-suites-run-single/Anchor.toml
  tests/multiple-suites-run-single/Cargo.toml
  tests/multiple-suites-run-single/package.json
  tests/multiple-suites-run-single/programs/multiple-suites-run-single/Cargo.toml
  tests/multiple-suites-run-single/programs/multiple-suites-run-single/Xargo.toml
  tests/multiple-suites-run-single/programs/multiple-suites-run-single/src/lib.rs
  tests/multiple-suites-run-single/tests/should-not-run/Test.toml
  tests/multiple-suites-run-single/tests/should-not-run/shouldNotRun.ts
  tests/multiple-suites-run-single/tests/should-run/Test.toml
  tests/multiple-suites-run-single/tests/should-run/shouldRun.ts
  tests/multiple-suites-run-single/tsconfig.json
  tests/package.json
Labels: waiting for tests to run

#2301 Identity com bugfix/robust fetch nullable
  CHANGELOG.md
  tests/misc/tests/misc/misc.ts
  ts/packages/anchor/src/program/namespace/account.ts
Labels: waiting for tests to run

#2101 Feat: Optional Positional Accounts
  .github/workflows/no-cashing-tests.yaml
  .github/workflows/tests.yaml
  client/example/Cargo.toml
  client/example/run-test.sh
  client/example/src/main.rs
  lang/Cargo.toml
  lang/derive/accounts/Cargo.toml
  lang/src/accounts/mod.rs
  lang/src/accounts/option.rs
  lang/src/error.rs
  lang/syn/Cargo.toml
  lang/syn/src/codegen/accounts/__client_accounts.rs
  lang/syn/src/codegen/accounts/__cpi_client_accounts.rs
  lang/syn/src/codegen/accounts/constraints.rs
  lang/syn/src/codegen/accounts/exit.rs
  lang/syn/src/codegen/accounts/to_account_infos.rs
  lang/syn/src/codegen/accounts/to_account_metas.rs
  lang/syn/src/codegen/accounts/try_accounts.rs
  lang/syn/src/idl/file.rs
  lang/syn/src/idl/mod.rs
  lang/syn/src/lib.rs
  lang/syn/src/parser/accounts/mod.rs
  tests/misc/Anchor.toml
  tests/misc/programs/misc-optional/Cargo.toml
  tests/misc/programs/misc-optional/Xargo.toml
  tests/misc/programs/misc-optional/src/account.rs
  tests/misc/programs/misc-optional/src/context.rs
  tests/misc/programs/misc-optional/src/event.rs
  tests/misc/programs/misc-optional/src/lib.rs
  tests/misc/tests/misc/misc.ts
  tests/optional/Anchor.toml
  tests/optional/Cargo.toml
  tests/optional/package.json
  tests/optional/programs/allow-missing-optionals/Cargo.toml
  tests/optional/programs/allow-missing-optionals/Xargo.toml
  tests/optional/programs/allow-missing-optionals/src/lib.rs
  tests/optional/programs/optional/Cargo.toml
  tests/optional/programs/optional/Xargo.toml
  tests/optional/programs/optional/src/account.rs
  tests/optional/programs/optional/src/context.rs
  tests/optional/programs/optional/src/lib.rs
  tests/optional/tests/optional.ts
  tests/optional/tsconfig.json
  tests/package.json
  tests/yarn.lock
  ts/build-packages.sh
  ts/packages/anchor/src/error.ts
  ts/packages/anchor/src/idl.ts
  ts/packages/anchor/src/program/accounts-resolver.ts
  ts/packages/anchor/src/program/context.ts
  ts/packages/anchor/src/program/namespace/instruction.ts
  ts/packages/anchor/src/program/namespace/methods.ts
  ts/packages/anchor/src/program/namespace/state.ts
Labels: waiting for review

#2310 Only add public enums to the IDL
  CHANGELOG.md
  lang/syn/src/idl/file.rs
Labels: waiting for tests to run

#1923 cli: `anchor account` subcommand to read program account
  .github/workflows/no-cashing-tests.yaml
  .github/workflows/tests.yaml
  CHANGELOG.md
  cli/src/lib.rs
  docs/src/pages/docs/cli.md
  lang/syn/src/idl/mod.rs
  tests/anchor-cli-account/Anchor.toml
  tests/anchor-cli-account/Cargo.toml
  tests/anchor-cli-account/package.json
  tests/anchor-cli-account/programs/account-command/Cargo.toml
  tests/anchor-cli-account/programs/account-command/Xargo.toml
  tests/anchor-cli-account/programs/account-command/src/lib.rs
  tests/anchor-cli-account/tests/account.ts
  tests/anchor-cli-account/tsconfig.json
  tests/package.json
Labels: waiting for tests to run

#2325 Allow passing env vars to verifiable build container
  CHANGELOG.md
  cli/src/lib.rs
Labels: waiting for tests to run

#2332 Cli: Don't regenerate idl in read_all_programs()
  CHANGELOG.md
  cli/src/config.rs
Labels: waiting for tests to run
