Repository solana-foundation/anchor, pull requests merged in 2023-02, with the labels that each got.

#2321 Multithreaded Client
  CHANGELOG.md
  client/example/run-test.sh
  client/example/src/main.rs
  client/src/lib.rs
Labels: waiting for review

#2322 add async_rpc method
  CHANGELOG.md
  client/src/lib.rs
Labels: waiting for review

#2370 cli: fixes bug where the wrong exit status is reported
  CHANGELOG.md
  avm/src/anchor/main.rs
Labels: waiting for review

#2375 lang: remove deprecated accounts
  CHANGELOG.md
  lang/src/accounts/cpi_account.rs
  lang/src/accounts/loader.rs
  lang/src/accounts/mod.rs
  lang/src/accounts/program_account.rs
  lang/syn/src/codegen/accounts/constraints.rs
  lang/syn/src/lib.rs
  lang/syn/src/parser/accounts/constraints.rs
  lang/syn/src/parser/accounts/mod.rs
  tests/chat/programs/chat/src/lib.rs
  tests/misc/programs/misc-optional/src/context.rs
  tests/misc/programs/misc/src/context.rs
  tests/misc/programs/misc/src/lib.rs
  tests/multisig/programs/multisig/src/lib.rs
Labels: waiting for review

#2379 lang: remove ConstraintLiteral
  CHANGELOG.md
  Cargo.lock
  lang/syn/Cargo.toml
  lang/syn/src/codegen/accounts/constraints.rs
  lang/syn/src/lib.rs
  lang/syn/src/parser/accounts/constraints.rs
Labels: waiting for review

#2387 add --skip-build option for verify command
  CHANGELOG.md
  cli/src/lib.rs
Labels: waiting for tests to run

#2391 reqwest change uwuwu
  CHANGELOG.md
  Cargo.lock
  avm/Cargo.lock
  avm/Cargo.toml
  cli/Cargo.toml
Labels: waiting for tests to run

#2390 Make the return type of `AccountClient.fetchMultiple` consistent
  CHANGELOG.md
  ts/packages/anchor/src/program/namespace/account.ts
Labels: Looks fine?

#2386 interface: Support multiple programs with the same interface via token-2022
  Cargo.lock
  lang/src/accounts/account.rs
  lang/src/accounts/interface.rs
  lang/src/accounts/interface_account.rs
  lang/src/accounts/mod.rs
  lang/src/accounts/program.rs
  lang/src/lib.rs
  lang/syn/src/codegen/accounts/constraints.rs
  lang/syn/src/lib.rs
  lang/syn/src/parser/accounts/mod.rs
  spl/Cargo.toml
  spl/src/associated_token.rs
  spl/src/lib.rs
  spl/src/token_2022.rs
  spl/src/token_interface.rs
  tests/escrow/Anchor.toml
  tests/escrow/programs/escrow/Cargo.toml
  tests/escrow/programs/escrow/src/lib.rs
  tests/escrow/tests/escrow.ts
  tests/spl/token-proxy/Anchor.toml
  tests/spl/token-proxy/programs/token-proxy/Cargo.toml
  tests/spl/token-proxy/programs/token-proxy/src/lib.rs
  tests/spl/token-proxy/tests/token-proxy.js
Labels: waiting for review

#2406 Minor typo in private type
  spl/src/associated_token.rs
Labels: Looks fine?
