Repository solana-foundation/anchor, pull requests merged in 2023-01, with the labels that each got.

#2329 Idl: Limit account size to 60kb, allow closing idl accounts
  CHANGELOG.md
  cli/src/lib.rs
  lang/src/error.rs
  lang/src/idl.rs
  lang/syn/src/codegen/program/handlers.rs
  tests/anchor-cli-idl/test.sh
  tests/anchor-cli-idl/tests/idl.ts
Labels: waiting for tests to run

#2331 Simulate: Don't attempt to sign transaction
  CHANGELOG.md
  ts/packages/anchor/src/provider.ts
Labels: waiting for review

#2362 Fix clippy lints
  avm/src/lib.rs
  cli/src/config.rs
  cli/src/lib.rs
  lang/syn/src/parser/context.rs
Labels: waiting for tests to run

#2364 Updated release-notes
  docs/src/pages/docs/release-notes.md
Labels: Looks fine?

#2367 introduce idl account getter
  ts/packages/anchor/src/program/namespace/account.ts
Labels: Looks fine?

#2357 ts: remove duplicate functions
  CHANGELOG.md
  tests/bpf-upgradeable-state/tests/bpf-upgradable-state.ts
  tests/pda-derivation/tests/typescript.spec.ts
  ts/packages/anchor/src/utils/pubkey.ts
  ts/packages/anchor/src/utils/rpc.ts
  ts/packages/anchor/src/utils/token.ts
Labels: Looks fine?

#2346 lang: add the InitSpace macro
  CHANGELOG.md
  Cargo.lock
  lang/Cargo.toml
  lang/derive/space/Cargo.toml
  lang/derive/space/src/lib.rs
  lang/src/lib.rs
  lang/tests/space.rs
  tests/chat/programs/chat/src/lib.rs
  tests/ido-pool/programs/ido-pool/src/lib.rs
Labels: blocked, Looks fine?

#2365 Update IDL program
  CHANGELOG.md
  lang/src/ctor.rs
  lang/src/idl.rs
  lang/src/lib.rs
  lang/syn/src/codegen/program/dispatch.rs
  lang/syn/src/codegen/program/handlers.rs
  lang/syn/src/codegen/program/idl.rs
  lang/syn/src/codegen/program/mod.rs
Labels: waiting for tests to run

#2330 Make zero copy safe by default, add `account(zero_copy(unsafe))` feature.
  CHANGELOG.md
  lang/attribute/account/src/lib.rs
  lang/tests/generics_test.rs
  tests/chat/programs/chat/Cargo.toml
  tests/misc/programs/misc-optional/Cargo.toml
  tests/misc/programs/misc/Cargo.toml
  tests/zero-copy/programs/zero-copy/Cargo.toml
  tests/zero-copy/programs/zero-copy/src/lib.rs
Labels: Looks fine?
