Repository solana-foundation/anchor, pull requests merged in 2024-03, with the labels that each got.

#2819 add doc for scenario of burning a nft part of a collection.
  spl/src/metadata.rs
Labels: documentation, spl

#2843 ts: Make `opts` parameter of `AnchorProvider` constructor optional
  .github/workflows/reusable-tests.yaml
  CHANGELOG.md
  ts/packages/anchor/src/provider.ts
Labels: ts

#2847 cli: Add `--no-idl` flag to the `build` command
  CHANGELOG.md
  cli/src/lib.rs
Labels: cli

#2852 docs: Refactor sidebar navigation
  docs/src/pages/_app.jsx
  docs/src/pages/release-notes/0.29.0.md
  docs/src/pages/release-notes/changelog.md
Labels: documentation

#2845 cli: Add priority fees to idl commands
  CHANGELOG.md
  cli/src/lib.rs
Labels: cli

#2859 Upgrade `cargo_toml` to 0.19.2
  Cargo.lock
  avm/Cargo.toml
  cli/Cargo.toml
  lang/syn/Cargo.toml
Labels: dependencies

#2860 chore: fix typos
  docs/src/pages/docs/publishing-source.md
  examples/tutorial/basic-5/tests/basic-5.ts
  lang/syn/src/codegen/accounts/try_accounts.rs
Labels: documentation

#2864 ts: Remove `programId` parameter of the `Program` constructor
  CHANGELOG.md
  tests/auction-house/tests/auction-house.ts
  tests/misc/tests/misc/misc.ts
  tests/pda-derivation/tests/typescript.spec.ts
  tests/spl/token-proxy/tests/token-proxy.js
  ts/packages/anchor/src/native/system.ts
  ts/packages/anchor/src/program/accounts-resolver.ts
  ts/packages/anchor/src/program/index.ts
  ts/packages/anchor/src/workspace.ts
  ts/packages/spl-associated-token-account/src/program.ts
  ts/packages/spl-token/src/program.ts
Labels: ts, breaking

#2863 add optional prepend to preInstructions method builder
  CHANGELOG.md
  ts/packages/anchor/src/program/namespace/methods.ts
Labels: ts

#2857 lang: Add `declare_program!` macro
  CHANGELOG.md
  Cargo.lock
  lang/attribute/program/Cargo.toml
  lang/attribute/program/src/declare_program/common.rs
  lang/attribute/program/src/declare_program/mod.rs
  lang/attribute/program/src/declare_program/mods/accounts.rs
  lang/attribute/program/src/declare_program/mods/client.rs
  lang/attribute/program/src/declare_program/mods/constants.rs
  lang/attribute/program/src/declare_program/mods/cpi.rs
  lang/attribute/program/src/declare_program/mods/events.rs
  lang/attribute/program/src/declare_program/mods/internal.rs
  lang/attribute/program/src/declare_program/mods/mod.rs
  lang/attribute/program/src/declare_program/mods/program.rs
  lang/attribute/program/src/declare_program/mods/types.rs
  lang/attribute/program/src/lib.rs
  lang/src/lib.rs
  lang/syn/src/codegen/accounts/mod.rs
  tests/declare-program/Anchor.toml
  tests/declare-program/Cargo.toml
  tests/declare-program/idls/external.json
  tests/declare-program/package.json
  tests/declare-program/programs/declare-program/Cargo.toml
  tests/declare-program/programs/declare-program/Xargo.toml
  tests/declare-program/programs/declare-program/src/lib.rs
  tests/declare-program/programs/external/Cargo.toml
  tests/declare-program/programs/external/Xargo.toml
  tests/declare-program/programs/external/src/lib.rs
  tests/declare-program/tests/declare-program.ts
  tests/declare-program/tsconfig.json
  tests/package.json
Labels: lang, next

#2867 Upgrade Solana to 1.18.8
  .github/workflows/no-caching-tests.yaml
  .github/workflows/tests.yaml
  CHANGELOG.md
  Cargo.lock
  bench/BINARY_SIZE.md
  bench/COMPUTE_UNITS.md
  bench/STACK_MEMORY.md
  cli/Cargo.toml
  client/Cargo.toml
  client/example/Cargo.toml
  docker/Makefile
  lang/Cargo.toml
  setup-tests.sh
  spl/Cargo.toml
  tests/bench/bench.json
  tests/bench/tests/stack-memory.ts
  tests/escrow/Anchor.toml
  tests/spl/token-proxy/Anchor.toml
  tests/spl/token-wrapper/Anchor.toml
  tests/spl/transfer-hook/Anchor.toml
  tests/zero-copy/programs/zero-copy/Cargo.toml
Labels: ci, dependencies, next

#2873 ci: Add `declare-program` tests
  .github/workflows/reusable-tests.yaml
Labels: ci

#2874 cli: Standardize Rust templates for "anchor init" generated JSON and ignore files
  cli/src/rust_template.rs
Labels: cli

#2872 Add Deactivate Feature Flag to CLI Local Validator
  CHANGELOG.md
  cli/src/config.rs
  cli/src/lib.rs
Labels: cli

#2876 Upgrade `spl-token-2022` to 3.0.2
  CHANGELOG.md
  Cargo.lock
  bench/COMPUTE_UNITS.md
  spl/Cargo.toml
  tests/bench/bench.json
Labels: spl, dependencies
