Repository solana-foundation/anchor, pull requests merged in 2025-04, with the labels that each got.

#3638 docs: Fix broken links in v0.31.0 release notes
  docs/content/docs/updates/release-notes/0-31-0.mdx
Labels: documentation, fix

#3641 docs: clarify Vec space calculation in documentation
  docs/content/docs/references/space.mdx
Labels: documentation

#3654 Fix `clippy 1.86.0`
  avm/src/lib.rs
  lang/src/accounts/account_loader.rs
  lang/src/accounts/interface.rs
  lang/src/accounts/program.rs
  lang/syn/src/parser/program/instructions.rs
Labels: fix

#3663 fix: Update `proc-macro2` usage for latest nightly
  CHANGELOG.md
  Cargo.lock
  lang/syn/src/idl/defined.rs
Labels: idl, fix

#3656 Fix incorrect space recommendation description in docs
  docs/content/docs/references/space.mdx
Labels: documentation

#3665 ts: Fix parsing idl with multiple const generics
  CHANGELOG.md
  ts/packages/anchor/src/coder/borsh/idl.ts
  ts/packages/anchor/tests/coder-accounts.spec.ts
Labels: ts, fix
