Repository solana-foundation/anchor, pull requests merged in 2025-02, with the labels that each got.

#3528 docs: Add `engines.node` override in `package.json`
  docs/package.json
Labels: documentation, fix

#3534 Update account-constraints.mdx
  docs/content/docs/references/account-constraints.mdx
Labels: documentation

#3530 docs: add mollusk docs
  docs/content/docs/meta.json
  docs/content/docs/quickstart/local.mdx
  docs/content/docs/testing/index.mdx
  docs/content/docs/testing/meta.json
  docs/content/docs/testing/mollusk.mdx
Labels: documentation

#3531 cli: Convert package managers to lowercase during serialization
  cli/src/config.rs
Labels: cli, fix

#3537 fix: add `anchor-spl/idl-build` in idl-build feature list in documentation
  docs/content/docs/tokens/index.mdx
Labels: documentation

#3544 client: Remove `std::process::exit` usage
  CHANGELOG.md
  client/src/lib.rs
Labels: client, fix

#3549 ci: Fix `avm` tests
  .github/workflows/reusable-tests.yaml
Labels: ci, fix

#3559 idl: Fix using `Pubkey` constants with `seeds::program`
  CHANGELOG.md
  lang/syn/src/idl/accounts.rs
  tests/pda-derivation/programs/pda-derivation/src/lib.rs
  tests/pda-derivation/tests/typescript.spec.ts
Labels: idl, fix

#3561 docs: Update outdated documentation of `Context`
  docs/content/docs/basics/program-structure.mdx
Labels: documentation, fix

#3565 add litesvm docs to Testing Libraries section
  docs/content/docs/testing/litesvm.mdx
  docs/content/docs/testing/meta.json
Labels: documentation

#3570 idl: Fix using account or arg values for `seeds::program`
  CHANGELOG.md
  lang/syn/src/idl/accounts.rs
  tests/pda-derivation/programs/pda-derivation/src/lib.rs
  tests/pda-derivation/tests/typescript.spec.ts
Labels: idl, fix
