Repository solana-foundation/anchor, pull requests merged in 2025-03, with the labels that each got.

#3575 Docs: Add Inkeep AI Chat Widget and update Install page
  docs/app/components/inkeep-script.tsx
  docs/app/inkeep-settings.ts
  docs/app/layout.tsx
  docs/content/docs/installation.mdx
Labels: documentation

#3576 Fix `clippy 1.85.0`
  lang/attribute/account/src/lib.rs
Labels: fix

#3578 lang: Replace hardcoded discriminators with `Discriminator::DISCRIMINATOR`
  lang/attribute/program/src/declare_program/mods/cpi.rs
  lang/attribute/program/src/declare_program/mods/events.rs
Labels: lang

#3581 cli: Use camelCase for program name in `anchor.workspace` templates
  CHANGELOG.md
  cli/src/rust_template.rs
Labels: cli, fix

#3597 docs: Add Inkeep Searchbar
  docs/app/components/inkeep-script.tsx
  docs/app/components/inkeep/inkeep-chat-button.tsx
  docs/app/components/inkeep/inkeep-search.tsx
  docs/app/components/inkeep/useInkeepConfig.ts
  docs/app/inkeep-settings.ts
  docs/app/layout.tsx
  docs/app/provider.tsx
  docs/content/docs/installation.mdx
  docs/package.json
  docs/pnpm-lock.yaml
Labels: documentation

#3599 docs: Add shell completions section to installation page
  docs/content/docs/installation.mdx
  docs/content/docs/updates/release-notes/0-31-0.mdx
Labels: documentation

#3604 docs: update Inkeep to fix vercel deployment
  docs/package.json
  docs/pnpm-lock.yaml
Labels: documentation

#3605 docs: Add package manager documentation
  docs/content/docs/references/anchor-toml.mdx
  docs/content/docs/updates/release-notes/0-31-0.mdx
Labels: documentation

#3610 lang: Fix `bytemuck_derive` build error
  Cargo.lock
  lang/Cargo.toml
Labels: lang, dependencies, fix

#3601 fix(docs): some problem of code examples
  docs/content/docs/features/errors.mdx
Labels: documentation

#3611 Update errors.mdx
  docs/content/docs/features/errors.mdx
Labels: documentation

#3612 docs: update to use anchor 0.31.0
  docs/content/docs/basics/cpi.mdx
  docs/content/docs/basics/idl.mdx
  docs/content/docs/basics/program-structure.mdx
  docs/content/docs/clients/rust.mdx
  docs/content/docs/clients/typescript.mdx
  docs/content/docs/features/declare-program.mdx
  docs/content/docs/features/errors.mdx
  docs/content/docs/features/events.mdx
  docs/content/docs/features/zero-copy.mdx
  docs/content/docs/references/account-constraints.mdx
  docs/content/docs/references/account-types.mdx
  docs/content/docs/tokens/basics/create-mint.mdx
  docs/content/docs/tokens/basics/create-token-account.mdx
  docs/content/docs/tokens/extensions.mdx
  docs/content/docs/tokens/index.mdx
Labels: documentation

#3613 Make `Provider` require publicKey instead of wallet in accounts resolver
  CHANGELOG.md
  ts/packages/anchor/src/program/accounts-resolver.ts
Labels: ts, feature

#3630 lang: Remove `bytemuck_derive` version requirement
  Cargo.lock
  lang/Cargo.toml
Labels: lang, dependencies
